export const apiKey = 'd435574e14274ab8938174220233107';

export const weatherImages = {
    'Partly cloudy': require('../assets/images/suncloud.png'),
    'Moderate rain': require('../assets/images/raincloud.png'),
    'Patchy rain possible': require('../assets/images/raincloud.png'),
    'Sluníčkový piknik s obláčky': require('../assets/images/suncloud.png'),
    'Mírný deštíkový koncert': require('../assets/images/raincloud.png'),
    'Obláčky mohou pokapávat': require('../assets/images/raincloud.png'),
    'Clear': require('../assets/images/sun.png'),
    'Sunny': require('../assets/images/sun.png'),
    'Den plný sluníčkových úsměvů': require('../assets/images/sun.png'),
    'Overcast': require('../assets/images/cloud.png'),
    'Hustá obláčková párty': require('../assets/images/cloud.png'),
    'Šeptání dešťových kapek': require('../assets/images/raincloud.png'),
    'Občasné kapky pro radost': require('../assets/images/raincloud.png'),
    'Silný deštíkový koncert': require('../assets/images/raincloud.png'),
    'Obláčky občas hodně pláčou': require('../assets/images/raincloud.png'),
    'Zmrzlé kapky, malé nebo velké': require('../assets/images/raincloud.png'),
    'Obláčkové sprchování, malé nebo velké': require('../assets/images/raincloud.png'),
    'Bouřkový koncert pro velké i malé kapky': require('../assets/images/raincloud.png'),
    'Cloudy': require('../assets/images/cloud.png'),
    'Light rain': require('../assets/images/raincloud.png'),
    'Moderate rain at times': require('../assets/images/raincloud.png'),
    'Heavy rain': require('../assets/images/raincloud.png'),
    'Heavy rain at times': require('../assets/images/raincloud.png'),
    'Moderate or heavy freezing rain': require('../assets/images/raincloud.png'),
    'Moderate or heavy rain shower': require('../assets/images/raincloud.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/raincloud.png'),
    'Hra na schovávanou s kouzelnou mlhou': require('../assets/images/mist.png'),
    'Mist': require('../assets/images/mist.png'),
    'other': require('../assets/images/raincloud.png')
}